# See https://github.com/helix-editor/helix/wiki/Language-Server-Configurations

[language-server.openscad]
command = "openscad-lsp"


# https://nathanielknight.ca/articles/helix_for_python.html
# pipx install python-lsp-server
# pipx inject python-lsp-server python-lsp-ruff python-lsp-black
[language-server.pylsp.config.pylsp]
plugins.ruff.enabled = true
plugins.black.enabled = true

# rustup component add rust-analyzer
[[language]]
name="rust"
[language-server.rust-analyzer.config.check]
command = "clippy"
auto-format = true
diagnostic-severity = "error"


# For html+css: https://github.com/helix-editor/helix/wiki/Language-Server-Configurations#html
# npm i -g vscode-langservers-extracted
[[language]]
name = "html"
# language-server = { command = "html-languageserver", args = ["--stdio"] }
auto-format = false
auto-pairs = true
